version: "3"

services:
  cantaloupe:
    build: .
    image: cihm-cantaloupe
    networks:
      access-platform:
        ipv4_address: 172.30.0.5
    #ports:
    #  - "8182:8182"
    # environment:
    # - S3SOURCE_ENDPOINT=https://swifts3.endpoint/
    # - S3SOURCE_ACCESS_KEY_ID=swiftuser
    # - S3SOURCE_SECRET_KEY=swifts3secret
    # - S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME=test
    # - CANVAS_DB=http://couch.domain/canvas (do not add a trailing slash)
    # - CAP_JWT_SECRET=capjwtsecret
    # - AUTH_JWT_SECRET=authjwtsecret
networks:
  access-platform:
    external: true
